trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azure_connection: 'azurerm-connection'

stages:
- stage: Plan
  displayName: 'Terraform init & Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: AzureCLI@2
      displayName: 'Login to Azure using Service Connection'
      inputs:
        azureSubscription: '$(azure_connection)' # Authenticates and sets env vars
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Azure login successful via service connection."
          az account show
          # THIS TASK sets ARM_* environment variables for THIS JOB

    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
      # This task installs Terraform, doesn't necessarily need ARM auth here

    - script: |
        terraform --version
        cd terraform/dev
        # THIS SCRIPT RUNS TERRAFORM COMMANDS
        # It relies on the ARM_* environment variables set by the AzureCLI@2 task in the same job

        terraform init -backend-config="storage_account_name=$(storageAccountName)" -backend-config="container_name=$(containerName)" -backend-config="key=$(key)" -backend-config="access_key=$(accessKey)"
        terraform plan -out=tfplan
      displayName: 'Terraform Init and Plan'