trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azure_connection: 'azurerm-connection'

stages:
- stage: Azure_Auth 
  displayName: 'Auth Test'
  jobs:
  - job: AzureCLI
    displayName: 'Auth Test2'
    steps:
    - task: AzureCLI@2
      displayName: 'Login to Azure using Service Connection'
      inputs:
        azureSubscription: '$(azure_connection)' # Authenticates and sets env vars
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Azure login successful via service connection."
          az account show
- stage: Plan
  displayName: 'Terraform init & Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    - task: TerraformInstaller@0
      inputs:
        azureResourceManagerConnection: $(azure_connection)
        terraformVersion: 'latest'

    - script: |
        terraform --version
        cd terraform/dev
        terraform init -backend-config="storage_account_name=$(storageAccountName)" -backend-config="container_name=$(containerName)" -backend-config="key=$(key)" -backend-config="access_key=$(accessKey)"
        terraform plan -out=tfplan
      displayName: 'Terraform Init and Plan'