# Configuration for Prometheus
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: default # Or your preferred StorageClass
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi # Adjust as needed

# Configuration for Grafana
grafana:
  persistence:
    enabled: true
    storageClassName: default # Or your preferred StorageClass
    accessModes:
      - ReadWriteOnce
    size: 10Gi # Adjust as needed
