# Configuration for Prometheus
prometheus:
  prometheusSpec:
    maximumStartupDurationSeconds: 60
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: default # Or your preferred StorageClass
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi # Adjust as needed
  # Add service configuration for Prometheus
  service:
    type: LoadBalancer # Set service type to LoadBalancer for public IP

# Configuration for Grafana
grafana:
  persistence:
    enabled: true
    storageClassName: default # Or your preferred StorageClass
    accessModes:
      - ReadWriteOnce
    size: 10Gi # Adjust as needed
  # Add service configuration for Grafana
  service:
    type: LoadBalancer # Set service type to LoadBalancer for public IP